global:
  cluster: demo
  nrStaging: true

prometheus:
  # Automatically scrape prometheus metrics for annotated services in the cluster
  # Collecting prometheus metrics for large clusters might impact data usage significantly
  enabled: true
  lowDataMode: true  # Skip ingesting cluster-level metrics
kubeEvents:
  # Report Kubernetes events
  enabled: true
ksm:
  # Deploy kube-state-metrics in the cluster.
  # Set this to true unless it is already deployed.
  enabled: true