apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  namespace: opentelemetry-demo
  labels:
    app: opentelemetry
    component: otel-collector-agent
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector-agent
    spec:
      containers:
      - name: otel-collector-agent
        image: otel-collector-agent
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 4317
            hostPort: 4317
            protocol: TCP
        env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
      serviceAccountName: opentelemetry-collector-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector-agent
  namespace: opentelemetry-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-agent-role-binding
subjects:
  - kind: ServiceAccount
    name: opentelemetry-collector-agent
    namespace: opentelemetry-demo
roleRef:
  kind: ClusterRole
  name: otel-collector-agent-role
  apiGroup: rbac.authorization.k8s.io